# Generated by Django 4.2.1 on 2023-06-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='IMEI',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
