# Generated by Django 4.2.7 on 2024-02-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_deviceinfo_imei'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='is_drinkable',
            field=models.BooleanField(default=False),
        ),
    ]
